### ISSUE TITLE
Saturday School - Changes to Saturday School Page - (please do till June 5th)

### ISSUE THREAD

**Issue by BHuber-DSKI** [dskobe/website#41]
A. This is on the Admission page
https://www.dskobe.org/en/saturdayschool/admission/

Forms & Downloads (Okay as it is)
English School.....change to English Program

Online Application .....change to
Online Application (English Program)
English Saturday School Information PDF......change to
English Program Information PDF
Move to Learn.....change to Move to Learn Program

Online Application.....change to
Online Application (Move to Learn Program)
German/French School....change to German/French Program

Application for trial day (German school)........change to
Online Application (German program)
Application for trial day (French school).....change to
Online Application (German program)
German Saturday School Information PDF.....change to
German Program Information PDF
French Saturday School Information PDF.....change to
French Program Information PDF

B. This is on the English Program page
https://www.dskobe.org/en/saturdayschool/english-program/
Application Forms........change to Application Form
English School....change to English Program

Online Application Form........change to
Online Application (English Program)

C. This is on the German Program page
https://www.dskobe.org/en/saturdayschool/german-program/

Application Forms........change to Application Form
German School....change to German Program

Application for trial day (German school).....change to
Online Application (German Program)
D. This is on the French Program page
https://www.dskobe.org/en/saturdayschool/french-program/

Application Forms........change to Application Form
French School ....change to French Program

Application for trial day (French school).....change to
Online Application (French Program)
D. This is on the Move To Learn page
https://www.dskobe.org/en/saturdayschool/french-program/

Application Forms........change to Application Form
Move to Learn.......change to
Move to Learn Program

Online Application Form .......change to
Online Application (Move to Learn Program)
In addition please change all the spellings of the word program on the Saturday school titles and information as Program and not Programme as necessary to keep uniformity.

**Comment by dkastl** [comment]
There is already an issue with comments, see https://github.com/dskobe/internal/issues/1

If this should be done until till June 5th, then the review/translation of the new Japanese website content needs to be done by May 29th.

**Comment by dkastl** [comment]
Fixed in latest version
