### ISSUE TITLE
Saturday School Sign up forms - Change links to new ones - till May 26th

### ISSUE THREAD

**Issue by BHuber-DSKI** [dskobe/website#42]
This is important and urgent, because our Sign up period started in May. 

Please exchange all Saturday School sign up forms that have been shared with you in the Golden Week.

Move to Learn

English

German 

French

**Comment by dkastl** [comment]
It's already done, see https://github.com/dskobe/internal/issues/2

**Comment by dkastl** [comment]
Also updated on new website
