### ISSUE TITLE
Update Summer School page with Summer School blog

### ISSUE THREAD

**Issue by BHuber-DSKI** [dskobe/website#44]
https://summercampdski.blogspot.com/

Please post the link to the summer camp on the summer school page 

https://www.dskobe.org/en/programmes/summerschool/

![103833443_3149901758364429_5260457543168346555_n](https://user-images.githubusercontent.com/56827792/87124605-10d51500-c2c4-11ea-9836-8333a9a118ba.jpg)
![103748067_3149901745031097_4281348298777552167_n](https://user-images.githubusercontent.com/56827792/87124608-12064200-c2c4-11ea-93ed-48ed80e95de9.jpg)
![101358241_3127030643984874_6559504048542928209_n](https://user-images.githubusercontent.com/56827792/87124610-12064200-c2c4-11ea-8826-8d72c2d59b90.png)

Make

**Comment by dkastl** [comment]
Questions:

* what about the Japanese page?
* adding all these images to the page in the order above?
* shall I remove all the other content or keep it?

**Comment by dkastl** [comment]
Talked with Alex and updated it accordingly
