### ISSUE TITLE
Text for Remote Learning Programme with link in the navigator under "our programmes"

### ISSUE THREAD

**Issue by BHuber-DSKI** [dskobe/website#46]
Text is here: https://docs.google.com/document/d/1OvzrdbeTAvI-bVYKpYQ27uEsCqaEV3OoZSgvkFKgnc4/edit?usp=sharing
Shared with Daniel over Google Mail.

Please make a new page under our programmes with a link called "Remote Learning Programme" 
and put the text and pictures from the Google Doc on that page.

Japanese Version will follow.

**Comment by dkastl** [comment]
The images are difficult to get out from the Google Docs file.
Could you make them available on Google Drive?

**Comment by dkastl** [comment]
Found a trick to export the images.
In the end I didn't add all of them because it felt like too many images overall.
