### ISSUE TITLE
Link to English blog?

### ISSUE THREAD

**Issue by dkastl** [dskobe/website#47]
It's a bit weird to link to the Japanese blog from the non-Japanese page, see #45 .
There is actually an English blog, but it contains also links to "informal" blogs: https://dskiweekendnews.blogspot.com/

We need to decide if we want to link to this blog for the English page version.

**Comment by BHuber-DSKI** [comment]
Just Japanese at the moment. since the jap. blog is for promo reasons.

If it you don't want to put it on the mainpage then how about under the "community" bar in the navigator?

**Comment by dkastl** [comment]
It's already on the website.
I just thought it would be better to have the English page link to an English blog
