### ISSUE TITLE
Changes for Saturday School page

### ISSUE THREAD

**Issue by BHuber-DSKI** [dskobe/website#55]
Dear Benjamin,

I would appreciate it if you could please see that the following changes are made on our school website on the Saturday school pages.

1. In the Fees section under both the German Language and French Language programs please change the Books and Materials Fee from ¥3,000 to ¥5,000 i.e.
from this
Books and Materials Fee: ¥3,000
to this
Books and Materials Fee: ¥5,000

2.  Also on all three of the English, German and French Programs Online Application Forms after the section which says Medical Conditions and after the question
If you answered YES to any of the questions above, please explain in detail below. 
Please add the following question with a box below the question for them to write their answer like this.

Does your child have any special learning difficulties or behavioural issues which affect learning e.g. dyslexia, ADHD, etc.? 
O Yes (Kindly explain in detail below)

__________________________________________________________________________________________________________________________________

O No

Kindly let me know when this is done then I can check them. 
Thanks and kind regards,

Cecil

**Comment by dkastl** [comment]
Fees for Staruday School are in these two files:
- English: https://github.com/dskobe/website/blob/master/source/content/saturdayschool/fees.html.md.erb
- Japanese: https://github.com/dskobe/website/blob/master/source/content/saturdayschool/fees.ja.html.md.erb

Maybe a good idea to check if the other fees remain the same.

The file can be actually edited directly in Github.

**Comment by dkastl** [comment]
The forms are not managed through the website.

**Comment by dkastl** [comment]
I updated the fees for books and materials, closing this issue.
