### ISSUE TITLE
Request by Cecil - Saturday

### ISSUE THREAD

**Issue by BHuber-DSKI** [dskobe/website#57]
With regards to the Saturday school web pages and online application forms, etc. for now could you arrange to get all the information changed with relevance to the dates i.e. from 2020-2021 to 2021-2022 on all the relevant pages and all other relevant documents e.g. online application forms, re-enrollment forms etc. Will appreciate your conveying and arranging this with Daniel as necessary. 

___________________________

I already changed the dates on the google forms. please see if there has to be anything adjusted and changed on the website. - Benjamin

Thanks.

**Comment by dkastl** [comment]
OK. So basically preparing for the next school year, right? We somehow missued to update to the current one.

**Comment by dkastl** [comment]
The school schedule however is still the current one, because it's not finished yet:
https://www.dskobe.org/en/saturdayschool/schedule/
