### ISSUE TITLE
German patch shows error messages

### ISSUE THREAD

**Issue by BHuber-DSKI** [dskobe/website#61]
Hi Daniel,

![image](https://user-images.githubusercontent.com/56827792/139628692-b3d156ad-101a-493f-8858-cf2539631aa1.png)

The German page shows translations errors.

With kind regards
Benjamin

**Comment by dkastl** [comment]
Ah, thanks for posting as an issue. Will take a look.

**Comment by dkastl** [comment]
This is an interesting problem, because it does not happen when I run it locally. I think the menu language was always English if not Japanese, right? As far as I remember we never localized the menu to German or French.

**Comment by dkastl** [comment]
Should be resolved.
